---
- hosts: all
  sudo: yes
  tasks:
    - name: Install new dependencies
      apt: name={{ item }} state=present
      with_items:
        - expect
        - chromium-browser
    - name: Install Oracle Java
      command: ./install-oracle-java.sh
    - name: Install Maven
      apt: name=maven state=present
    - name: Install Eclipse
      command: ./install-eclipse.sh

